#
# Copyright (C) 2018 cmheia <cmheia@gmail.com>
#
# This is free software, licensed under the Apache License, Version 2.0
#

include $(TOPDIR)/rules.mk

LUCI_TITLE:=LuCI Support for vsftpd-pam
LUCI_DEPENDS:=+luci-compat +vsftpd-pam

PKG_LICENSE:=Apache-2.0

LUCI_PKGARCH:=all

PKG_MAINTAINER:=cmheia <cmheia@gmail.com>

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
